FROM node:20-alpine

WORKDIR /app

RUN corepack enable

# copy workspace config
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

# copy code
COPY apps ./apps
COPY packages ./packages

# install deps
RUN pnpm install --frozen-lockfile

# generate prisma
RUN pnpm --filter @repo/prisma exec prisma generate

# build next app
RUN pnpm turbo run build --filter=client

ENV NODE_ENV=production

EXPOSE 3000

CMD ["pnpm", "--filter", "client", "start"]